# Default graph URI http://sadiframework.org/registry/

PREFIX  dc:   <http://protege.stanford.edu/plugins/owl/dc/protege-dc.owl#>
PREFIX  sadi: <http://sadiframework.org/ontologies/sadi.owl#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  serv: <http://www.mygrid.org.uk/mygrid-moby-service#>

SELECT ?s
WHERE { 
  ?s rdf:type serv:serviceDescription .
  ?s rdf:type  sadi:Service .
  ?s  serv:hasOperation ?op .
  ?op serv:inputParameter ?input .
  ?input serv:objectType <http://purl.oclc.org/SADI/LSRN/UniProt_Record> 
}