PREFIX  dc:   <http://protege.stanford.edu/plugins/owl/dc/protege-dc.owl#>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  sadi: <http://sadiframework.org/ontologies/sadi.owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  owl:  <http://www.w3.org/2002/07/owl#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  serv: <http://www.mygrid.org.uk/mygrid-moby-service#>

SELECT ?s
WHERE { 
	  ?s rdf:type serv:serviceDescription .
	  ?s rdf:type  sadi:Service .
	  ?s  serv:providedBy ?org .
	  ?org  dc:creator ?auth .
	  ?org  dc:publisher  ?pub .
	  ?s dc:identifier ?name .
	  ?s sadi:decoratesWith ?out .
	  ?out owl:onProperty ?prop .
	  ?s serv:hasServiceDescriptionText $desc .
	  ?s serv:hasOperation ?op .
	  ?op serv:inputParameter ?inputP .
	  ?inputP  serv:objectType ?input .
	  ?op serv:outputParameter ?outputP .
	  ?outputP serv:objectType ?output
  }