#!/bin/sh

deploy_all(){

  # GET THE ARGUMENTS
  QUERY_DIR=$1
  ENDPOINT=$2 
  
  # CREATE LOCAL TOOL_CONF.XML FILE
  echo ""
  echo "INFO: Generating galaxy-dist/tool_conf.xml for the generic Galaxy tool, RDFSyntaxConverter and the SADI services defined in $QUERY_DIR"
  echo ""
  
  echo "	<section name=\"SADI services\" id=\"SADI\">" > galaxy-dist/tool_conf.xml
  echo "		<label text=\"SADI common utilities\" id=\"SADI-common-utilities\"/>" >> galaxy-dist/tool_conf.xml
  echo "			<tool file=\"SADI/sadi_generic.xml\"/>" >> galaxy-dist/tool_conf.xml
  echo "			<tool file=\"SADI/RDFSyntaxConverter.xml\"/>" >> galaxy-dist/tool_conf.xml
  echo "			<tool file=\"SADI/mergeRDFgraphs.xml\"/>" >> galaxy-dist/tool_conf.xml
  echo "		<label text=\"SADI services\" id=\"SADI-services\"/>" >> galaxy-dist/tool_conf.xml
  
  LIST=$QUERY_DIR"*"
  
  for QUERY in $LIST
    do
      echo "INFO: executing tool generator with $QUERY"
      java -jar sadi_tool_generator.jar $QUERY $ENDPOINT galaxy-dist/tool_conf.xml galaxy-dist/tools/SADI/ 2 > log 
    done
  echo "	</section>" >> galaxy-dist/tool_conf.xml
  echo "</toolbox>" >> galaxy-dist/tool_conf.xml
  echo ""
}

deploy(){
      echo ""
      echo "INFO: Generating galaxy-dist/tool_conf.xml for the generic Galaxy tool, RDF2TAB and RDFSyntaxConverter"
      echo ""
      echo "	<section name=\"SADI services\" id=\"SADI\">" > galaxy-dist/tool_conf.xml
      echo "		<label text=\"SADI common utilities\" id=\"SADI-common-utilities\"/>" >> galaxy-dist/tool_conf.xml
      echo "			<tool file=\"SADI/sadi_generic.xml\"/>" >> galaxy-dist/tool_conf.xml
      echo "			<tool file=\"SADI/RDFSyntaxConverter.xml\"/>" >> galaxy-dist/tool_conf.xml
      echo "			<tool file=\"SADI/mergeRDFgraphs.xml\"/>" >> galaxy-dist/tool_conf.xml
      echo "	</section>" >> galaxy-dist/tool_conf.xml
      echo "</toolbox>" >> galaxy-dist/tool_conf.xml
}


# CHECK ARGUMENTS AND EXECUTE

# Very basic argument checking !!!

if [ $# -eq 4 ];
  then
    deploy_all $3 $4
elif [ $# -eq 2 ];
  then
    deploy
else
  echo "ERROR: bad number of arguments, it should 2 or 4"
  echo ""
  echo "ARGUMENTS:"
  echo "  Absolut path to your Galaxy installation: /home/mikel/galaxy-dist/"
  echo "  Attempt to edit Galaxy tool_conf.xml (edit) or not (no_edit). If no_edit is selected (recommended), copy the lines from the generated tool_conf.xml to the tool_conf.xml of your galaxy server: edit|no_edit"
  echo "  (Optional) Path to dir qith SPARQL queries (use this to tune the retrieved SADI services): sparql/execute/"
  echo "  (Optional) SADI registry endpoint: http://dev.biordf.net/sparql/"
  echo ""
fi


# COPY THE NECCESARY FILES

GALAXY=$1
GALAXY_SADI=$GALAXY"tools/SADI/"

# Create SADI directory in server if it doesn't exist 
if [ ! -d $GALAXY_SADI ]; 
 then
   mkdir $GALAXY_SADI
fi
 
# Copy
cp galaxy-dist/tools/SADI/* $GALAXY_SADI
cp galaxy-dist/tool-data/shared/jars/sadi_generic_client.jar $GALAXY"/tool-data/shared/jars/"
cp galaxy-dist/tool-data/shared/jars/RDFSyntaxConverter.jar $GALAXY"/tool-data/shared/jars/"
cp galaxy-dist/tool-data/shared/errwrap.sh $GALAXY"/tool-data/shared/"
cp galaxy-dist/test-data/* $GALAXY"/test-data/" 


# EDIT TOOL_CONF.XML IN GALAXY SERVER INSTALLATION FOLLOWING NEW TOOL_CONF.XML (Generated by deploy or deploy_all), IF NECCESARY
if [ $2 = "edit" ];
  then
    
    # !!! Use with care !!! 
    # It will add the tool_conf.xml bit to the tool_confx.xml of the galaxy server you want SADI to be installed in
    # (SADI will appear at the end: it can also handle already existing SADI sections, if there are at the end, if they are not it 
    # will delete everything till </toolbox>, and you will have to recover from tool_conf.xml.bk)

    MAIN_TOOL_CONF=$GALAXY"tool_conf.xml"   
    TMP_TOOL_CONF=$GALAXY"tool_conf.xml.tmp"
    cp $MAIN_TOOL_CONF $galaxy"tool_conf.xml.bk"
    cat $MAIN_TOOL_CONF | sed '/<section name="SADI/,/<\/toolbox>/d' | grep -v "</toolbox>" > $TMP_TOOL_CONF
    less galaxy-dist/tool_conf.xml >> $TMP_TOOL_CONF
    mv $TMP_TOOL_CONF $MAIN_TOOL_CONF
    echo ""
    echo "INFO: Editing $MAIN_TOOL_CONF"
    echo ""
  else
    echo "INFO: Edit $GALAXY""tool_conf.xml by adding the content of ./galaxy-dist/tool_conf.xml to it"
    echo ""
fi





